## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - nightly
env:
  - JULIA_NUM_THREADS=2
notifications:
  email: false
git:
  depth: 99999999

matrix:
  allow_failures:
    - julia: nightly


after_success:
  # push coverage results to Coveralls
  - julia -e 'import Pkg, SequentialMonteCarlo; cd(joinpath(dirname(pathof(SequentialMonteCarlo)), "..")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # - julia -e 'cd(Pkg.dir("SequentialMonteCarlo")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'import Pkg, SequentialMonteCarlo; cd(joinpath(dirname(pathof(SequentialMonteCarlo)), "..")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  # - julia -e 'cd(Pkg.dir("SequentialMonteCarlo")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  # make documentation
  - julia -e 'import Pkg; Pkg.add("Documenter")'
  - julia -e 'SequentialMonteCarlo; cd(joinpath(dirname(pathof(SequentialMonteCarlo)), "..")); include(joinpath("docs", "make.jl"))'
  # - julia -e 'cd(Pkg.dir("SequentialMonteCarlo")); include(joinpath("docs", "make.jl"))'
