## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - nightly
notifications:
  email: false
git:
  depth: 99999999

matrix:
  allow_failures:
    - julia: nightly

## uncomment the following lines to override the default test script
# script:
 # - julia -e 'Pkg.clone(pwd()); Pkg.build("SequentialMonteCarlo")'
 # - JULIA_NUM_THREADS=2 julia -e 'Pkg.test("SequentialMonteCarlo"; coverage=true)'
 # - julia -e 'Pkg.clone(pwd()); Pkg.build("SequentialMonteCarlo"); Pkg.test("SequentialMonteCarlo"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'import Pkg, SequentialMonteCarlo; cd(dirname(pathof(SequentialMonteCarlo))); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # - julia -e 'cd(Pkg.dir("SequentialMonteCarlo")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'import Pkg, SequentialMonteCarlo; cd(dirname(pathof(SequentialMonteCarlo))); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  # - julia -e 'cd(Pkg.dir("SequentialMonteCarlo")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  # make documentation
  - julia -e 'import Pkg; Pkg.add("Documenter")'
  - julia -e 'SequentialMonteCarlo; cd(dirname(pathof(SequentialMonteCarlo))); include(joinpath("docs", "make.jl"))
  # - julia -e 'cd(Pkg.dir("SequentialMonteCarlo")); include(joinpath("docs", "make.jl"))'
